### ISSUE TITLE
接口调用回调无信息

### ISSUE THREAD

**Issue by ylj318** [TP-Lab/Mobile-SDK#11]
工程师，现在我通过安卓app接口发起了transfer接口，我看接口里面有个回调地址，但是我把回调地址加上去了（回调地址格式：http://xxx.xxx.xxx/cc/dd），没有看到有返回信息，还有如果没有接到，请问在哪里查询交易信息。谢谢

**Comment by NullPointerDuke** [comment]
更新到1.4.1版本试试
