### ISSUE TITLE
请问如何获取actionId

### ISSUE THREAD

**Issue by Deanllv** [TP-Lab/Mobile-SDK#12]
Android的demo中跳转tp钱包需要一个actionId的参数，请问这个是从哪获取的
另外是否可以从App内直接跳转到tp钱包的dapp内呢

**Comment by NullPointerDuke** [comment]
1 actionId是你自己设置的一个业务id，用来标记操作
2 参照https://github.com/TP-Lab/TokenPocket-Protocol#DappurlCallTokenPockettoopenurlwithDappbrowser

**Comment by Deanllv** [comment]
好的，了解，谢谢
