### ISSUE TITLE
Swift 接入sdk的时候崩溃

### ISSUE THREAD

**Issue by ct222** [TP-Lab/Mobile-SDK#17]
#5	0x000000010484b5b4 in __49-[TPPayResourceService loadResourceServiceConfig]_block_invoke at /Users/ica/repo/TPiOSSDK/TPSDK/TPSDK/PayResource/TPPayResourceService.m:107
签名成功返回app时在这里崩溃

**Comment by ct222** [comment]
用OC 不传wallet字段的时候也崩溃

**Comment by ct222** [comment]
咱们支持eth测试链的签名以及交易不

**Comment by heipacker** [comment]
> 咱们支持eth测试链的签名以及交易不

支持

**Comment by Andy870903** [comment]
请问支持tron交易吗？ios可以调起登陆授权 但交易失败

**Comment by Andy870903** [comment]
请问 ios支持tron交易吗？拉起账号登陆授权可以 但是交易失败了

**Comment by justXyS** [comment]
支持

**Comment by Andy870903** [comment]
>能帮我解答下疑惑吗  我用的是ios的SDK  接入就是交易失败，谢谢！

**Comment by justXyS** [comment]
麻烦提供下具体的错误信息
