### ISSUE TITLE
请教安卓SDK不能拉起兑换币的操作

### ISSUE THREAD

**Issue by hongri-xiao** [TP-Lab/Mobile-SDK#18]
大佬:们
         我要用安卓的SDK来完成 TRX(波场币)->USDT 的兑换, DEMO中的一些参数不知道怎么传递? 请指点下吗?

**Comment by NullPointerDuke** [comment]
暂时不支持这个操作

**Comment by heipacker** [comment]
> 大佬:们 我要用安卓的SDK来完成 TRX(波场币)->USDT 的兑换, DEMO中的一些参数不知道怎么传递? 请指点下吗?

https://docs.transit.finance/transit-docs/reference/api-reference

你可以看下这个接口文档， 然后调用SDK来签名就行了
