### ISSUE TITLE
如何验证TP钱包的签名

### ISSUE THREAD

**Issue by littlebencong** [TP-Lab/Mobile-SDK#19]
安卓使用SDK进行信息签名:
https://github.com/TP-Lab/Mobile-SDK/blob/6b5a00234c6b7adbdcb6a9ac08954299259624eb/Android%20SDK/SDK_DEMO/app/src/main/java/tokenpocket/pro/sdk_demo/eth/EthSignActivity.java#L43

签名完成后如何对已签名的信息进行校验？

**Comment by langxing** [comment]
兄弟，你的可以回调TPListerner吗？我的为啥授权后，回到App没有回调呢。

**Comment by Developmc** [comment]
你是怎么实现，测试设备信息这些贴一下

**Comment by Developmc** [comment]
> 兄弟，你的可以回调TPListerner吗？我的为啥授权后，回到App没有回调呢。

https://github.com/TP-Lab/Mobile-SDK/issues/48#issuecomment-2552675249
跟这个issues是同一个问题，在这个issues下讨论呗。

**Comment by Developmc** [comment]
> 安卓使用SDK进行信息签名:
> 
> https://github.com/TP-Lab/Mobile-SDK/blob/6b5a00234c6b7adbdcb6a9ac08954299259624eb/Android%20SDK/SDK_DEMO/app/src/main/java/tokenpocket/pro/sdk_demo/eth/EthSignActivity.java#L43
> 
> 签名完成后如何对已签名的信息进行校验？

用 web3.eth.accounts.recover 或 ethers.utils.verifyMessage
