### ISSUE TITLE
This is an iOS question.

### ISSUE THREAD

**Issue by parktaeyun** [TP-Lab/Mobile-SDK#23]
#import "AppDelegate.h"
#import <TPSDK/TPSDK.h>

@interface AppDelegate ()

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    [TPApi registerAppID:@"demoapp"];
    
    [TPApi enableLog:YES];
    [TPApi setPayResourceSwitch:YES forAccount:@"verycoolcool"];

    NSError *err;
    [TPApi setSeed:@"12345678" error:&err];
    if (err) {
        NSLog(@"%@", err.localizedDescription);
    }
    
    [TPApi setBlockChain:TPBlockChainTypeEOSMainNet nodeUrl:@"http://eosinfo.mytokenpocket.vip" plugNodeUrl:@"http://eosinfo.mytokenpocket.vip"];
    
    return YES;
}

code :  [TPApi enableLog:YES]; <---- error
-[NSUserDefaults tb_setObject:forKey:inGroup:]: unrecognized selector sent to instance 0x28243c0c0 <--- 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSUserDefaults tb_setObject:forKey:inGroup:]: unrecognized selector sent to instance 0x2812ee940'
*** First throw call stack:
(0x19b40b928 0x1af1aa480 0x19b31a960 0x19b40df84 0x19b40ff2c 0x102274a0c 0x102276130 0x102272190 0x19dcad7b0 0x19dcaf150 0x19dcb4f24 0x19d3878c0 0x19d8ac2c8 0x19d3883a8 0x19d387eb0 0x19d3881d4 0x19d387a90 0x19d38f72c 0x19d7c638c 0x19d8c4184 0x19d38f420 0x19d1ceae4 0x19d1cd590 0x19d1ce730 0x19dcb30fc 0x19d7eca84 0x1a9eeed00 0x1a9f164fc 0x1a9efc420 0x1a9f16214 0x10262d32c 0x1026307e4 0x1a9f3ae04 0x1a9f3aacc 0x1a9f3afa0 0x19b38afa8 0x19b38aea8 0x19b38a1fc 0x19b384718 0x19b383ed0 0x1b1acf570 0x19dcb12d0 0x19dcb684c 0x102273b18 0x19b062140)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSUserDefaults tb_setObject:forKey:inGroup:]: unrecognized selector sent to instance 0x2812ee940'
terminating with uncaught exception of type NSException

May I know what is causing the error?
A framework has also been added to see additional sample code.

**Comment by justXyS** [comment]
Build Settings -> Other linker Flags add '-ObjC'
