### ISSUE TITLE
Please add the application motion/sport data permission

### ISSUE THREAD

**Issue by Tyler-Franklin** [TP-Lab/Mobile-SDK#25]
Some sports-related dapps need to capture mobile device motion/sport data.

**Comment by Developmc** [comment]
Specifically, may i know what permissions you need

**Comment by Tyler-Franklin** [comment]
> Specifically, may i know what permissions you need 

Read device motion data

**Comment by Developmc** [comment]
Can you specify the permissions? 

For example(Android):
android.permission.ACTIVITY_RECOGNITION ?

**Comment by Tyler-Franklin** [comment]
> Can you specify the permissions? 
> 
> For example(Android):
> android.permission.ACTIVITY_RECOGNITION ?
> 
> 
> 
> 
> 

permission.READ_STEPS

**Comment by Developmc** [comment]
ok ，We will add this permission for android in the next version.(maybe version 1.5.5)

By the way, What permissions does iOS need for you?
