### ISSUE TITLE
IOS SDK怎么登陆polygon/matic网络？

### ISSUE THREAD

**Issue by dovegalss** [TP-Lab/Mobile-SDK#28]
使用以下代码，始终找不到网络。

    login.blockchains = @[
        [TPChainObj objWithNetwork:@"matic" chainId:@"1"],
        [TPChainObj objWithNetwork:@"eth" chainId:@"56"],
        [TPChainObj objWithNetwork:@"ethereum" chainId:@"56"]
    ];
    login.wallet = @"TokenPocket";
    
  
    
    [TPApi sendObj:login];

**Comment by justXyS** [comment]
matic是ethereum系列，chainid是137，代码如下：
login.blockchains = @[
    [TPChainObj objWithNetwork:@"ethereum" chainId:@"137"]
];
