### ISSUE TITLE
集成后崩溃问题

### ISSUE THREAD

**Issue by shihao123** [TP-Lab/Mobile-SDK#30]
打开打印 或者授权登录以后 app会崩溃
[TPApi enableLog:YES];

![image](https://user-images.githubusercontent.com/12841106/185016560-c8950c31-c7a4-45b3-a654-408da2ec5a1d.jpeg)

**Comment by justXyS** [comment]
在项目的Build Settings里面的0ther Linker Flags添加 -ObjC

**Comment by shihao123** [comment]
感谢 解决了
