### ISSUE TITLE
为什么安卓端发起转账，调用的波场链，success和回调都没有返回txId。

### ISSUE THREAD

**Issue by Fanstay** [TP-Lab/Mobile-SDK#41]
返回结果如下：
{"txID":"","account":"TRbwME21SgmAtpfJqxg2whfEiTt5zWuvKu","chainId":"728126428","network":"tron","ref":"TokenPocket","result":1,"wallet":"TRbwME21SgmAtpfJqxg2whfEiTt5zWuvKu","action":"transfer","actionId":"269647312882634752","protocol":"TokenPocket","version":"1.0.5"}

**Comment by Developmc** [comment]
感谢反馈，这个txID近期会加上
