### ISSUE TITLE
安卓和ios都能自动调起app了，给H5也安排上啊，能有几个app需要调起钱包啊，现在火的不都是dapp

### ISSUE THREAD

**Issue by lancesf** [TP-Lab/Mobile-SDK#8]

**Comment by Angolfire** [comment]
https://github.com/TP-Lab/Mobile-SDK/issues/8#issue-943678951

**Comment by Angolfire** [comment]
Good hoy

**Comment by chendatony31** [comment]
https://github.com/TP-Lab/TokenPocket-Protocol

https://github.com/TP-Lab/tp-js-sdk

@lancesf

**Comment by Angolfire** [comment]
> [#8 (comment)](https://github.com/TP-Lab/Mobile-SDK/issues/8#issue-943678951)

https://github.com/TP-Lab/Mobile-SDK/issues/8#issue-943678951

**Comment by Angolfire** [comment]
I just want to thank the people that helped me and are honest

**Comment by Angolfire** [comment]
Iam not getting message
